# Generated by Django 4.1.5 on 2023-01-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rus', models.CharField(max_length=25)),
                ('eng', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Все слова приложения',
                'verbose_name_plural': 'Все слова приложения',
            },
        ),
    ]
