# Generated by Django 4.1.5 on 2023-01-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEngAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_answer', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Ответ пользователя на английском',
                'verbose_name_plural': 'Ответ пользователя на английском',
            },
        ),
    ]
