# Generated by Django 4.1.5 on 2023-01-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_userenganswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenganswer',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userenganswer',
            name='eng_answer',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
